"""Add comments table

Revision ID: 7e23f3350978
Revises: e2412789c190
Create Date: 2024-06-09 19:12:21.275583

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '7e23f3350978'
down_revision = 'e2412789c190'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
     op.create_table(
        "comment",
        sa.Column("text", sa.VARCHAR(), nullable=False),
        sa.Column("id", sa.Integer(), nullable=False, autoincrement=True),
        sa.Column("date", sa.DateTime(), nullable=False),
        sa.Column("owner_id", sa.Integer(), nullable=False),
        sa.Column("zu_id", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(
            ["owner_id"],
            ["user.id"],
        ),
        sa.ForeignKeyConstraint(
            ["zu_id"],
            ["zu.gid"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
     
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
     op.drop_table("comment")
    # ### end Alembic commands ###
